/control/verbose 0
/run/verbose 0

#/testhadr/ionPhysics   UrQMD
/testhadr/ionPhysics       FTFP_BERT 
#QBBC

/run/initialize
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
#/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 90. 0.

# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 10 mm
# Axes, scale, etc.



/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set gamma grey
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton red
/vis/viewer/set/background white

/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
#/vis/verbose warnings
/run/beamOn 1
